### ISSUE TITLE
request for releasing pretrained LMs

### ISSUE THREAD

**Issue by tagucci** [raphael-sch/HC_Sentence_Summarization#2]
I read your interesting paper in ACL2020:)
I want to run your sentence compression code, but it requires forward/backward LM pretraining, sent2vec model training, and idf counting. Do you have a plan to release these pretrained models?

**Comment by raphael-sch** [comment]
Hi, I plan to write a better README which explains how to train and use the models. I don't have access to my original trained models anymore but I know of someone who was able to reproduce the results in the paper and will ask him if he can release his.

**Comment by raphael-sch** [comment]
I retrained the model to reproduce the results for the HC title models. Let me know if you need more information. Sorry for the looong delay.
